WebMVC/Models/JobProfile.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebMVC.Models
{
    public class JobProfile
    {
        [Key]
        public int Id { get; set; }
        public DateTime CreatedAt { get; set; } = DateTime.Now;
        [Required(ErrorMessage = "Email requerido")]
        [EmailAddress(ErrorMessage = "Ingrese un email válido")]
        [Display(Name = "Email de recepción")]
        public string EmailReceptor { get; set; }
        [Required(ErrorMessage = "Fecha de inicio requerida")]
        [Display(Name = "Fecha de inicio")]
        public DateTime StartingDate { get; set; }
        [Required(ErrorMessage = "Fecha de fin requerida")]
        [Display(Name = "Fecha de finalización")]
        public DateTime EndingDate { get; set; }
        [Required(ErrorMessage = "Dirección requerida")]
        [Display(Name = "Dirección")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Capacidad requerida")]
        [Display(Name = "Capacidad")]
        public int Capacity { get; set; }
        [Display(Name = "Descripción")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Posición requerida")]
        [Display(Name = "Puesto de trabajo")]
        public string Position { get; set; }
        [Display(Name = "Tipo")]
        public string Type { get; set; }
        public bool Status { get; set; }
        [ForeignKey("Company")]
        public int CompanyId { get; set; }
        public Company Company { get; set; }
        public ICollection<JobProfilePerson> JobProfilePerson { get; set; }
        public ICollection<Career> Careers { get; set; }
        public Internship Internship { get; set; }
        public Relationship Relationship { get; set; }

    }
}

WebMVC/Controllers/JobProfileController.cs
using BolsaTrabajo.Models.Db;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using WebMVC.Models;

namespace WebMVC.Controllers
{
    public class JobProfileController : Controller
    {
        private readonly BolsaTrabajoContext _context;

        public JobProfileController(BolsaTrabajoContext context)
        {
            _context = context;

        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Add()
        {

            if(HttpContext.Session.GetString("Id") != null && HttpContext.Session.GetString("Type") == "Company")
            {
                return View();
            } else
            {
                return Redirect("/");
            }
        }

        [HttpPost]
        public IActionResult Add(Models.JobProfile jobProfile)
        {
            jobProfile.CompanyId = int.Parse(HttpContext.Session.GetString("Id"));

            _context.JobProfiles.Add(jobProfile);
            _context.SaveChanges();

            return Redirect("/Company/Proposals");
        }

        public IActionResult Edit(int id)
        {

            if (HttpContext.Session.GetString("Id") != null && HttpContext.Session.GetString("Type") == "Company")
            {
                Models.JobProfile jp = _context.JobProfiles.Where(jp => jp.Id == id).FirstOrDefault();

                if (jp != null)
                {
                    return View(jp);
                }

                return Redirect("/Company/Proposals");
            }
            else
            {
                return Redirect("/");
            }
        }

        [HttpPost]
        public IActionResult Edit(Models.JobProfile jobProfile)
        {
            jobProfile.CompanyId = int.Parse(HttpContext.Session.GetString("Id"));

            _context.JobProfiles.Update(jobProfile);
            _context.SaveChanges();

            return Redirect("/Company/Proposals");
        }

        public IActionResult Delete(int id)
        {
            if (HttpContext.Session.GetString("Id") != null && HttpContext.Session.GetString("Type") == "Company")
            {
                Models.JobProfile jp = _context.JobProfiles.Where(jp => jp.Id == id).FirstOrDefault();

                if (jp != null)
                {

                    _context.Remove(jp);

                    _context.SaveChanges();
                }

                return Redirect("/Company/Proposals");
            }

            return Redirect("/");
        }

        public IActionResult ModifyProposal(int id, string state)
        {
            JobProfilePerson jobProfilePerson = _context.JobProfilePerson.Where(jpp => jpp.Id == id).FirstOrDefault();

            if(jobProfilePerson != null)
            {
                jobProfilePerson.Status = state;
                _context.Update(jobProfilePerson);
                _context.SaveChanges();
            }

            return Redirect("/Company/Proposals");
        }
    }
}

WebMVC/Views/JobProfile/Add.cshtml
@model WebMVC.Models.JobProfile;

@{
    ViewData["Title"] = "Add Proposal";
}

<div style="background:#E3E2E2;height:calc(100% - 56px);font-family: 'Roboto', sans-serif;" class="row px-3 overflow-auto">
    <div class="col-md-12">
        <h2 class="text-secondary my-3">
            Agregar Propuesta de Trabajo
        </h2>
        <div class="card">
            <div class="card-body">
                <form asp-controller="JobProfile" asp-action="Add" method="POST">
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label asp-for="StartingDate" class="control-label"></label>
                            <input type="date" asp-for="StartingDate" class="form-control" />
                            <span asp-validation-for="StartingDate" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="EndingDate" class="control-label"></label>
                            <input type="date" asp-for="EndingDate" class="form-control" />
                            <span asp-validation-for="EndingDate" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-4">
                            <label asp-for="Address" class="control-label"></label>
                            <input type="text" asp-for="Address" class="form-control" />
                            <span asp-validation-for="Address" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-4">
                            <label asp-for="Capacity" class="control-label"></label>
                            <input type="number" asp-for="Capacity" class="form-control" />
                            <span asp-validation-for="Capacity" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-4">
                            <label asp-for="Position" class="control-label"></label>
                            <input type="text" asp-for="Position" class="form-control" />
                            <span asp-validation-for="Position" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label asp-for="EmailReceptor" class="control-label"></label>
                            <input type="text" asp-for="EmailReceptor" class="form-control" />
                            <span asp-validation-for="EmailReceptor" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="Type" class="control-label"></label>
                            <select class="form-control" asp-for="Type">
                                <option value="Relationship">Relación de Dependencia</option>
                                <option value="Internship">Pasantía</option>
                            </select>
                            <span asp-validation-for="Type" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea style="resize:none" type="text" asp-for="Description" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group row justify-content-center">
                        <input type="submit" value="Agregar" class="btn btn-primary w-75" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

WebMVC/Views/JobProfile/Edit.cshtml
@model WebMVC.Models.JobProfile;

@{
    ViewData["Title"] = "Edit Proposal";
}

<div style="background:#E3E2E2;height:calc(100% - 56px);font-family: 'Roboto', sans-serif;" class="row px-3 overflow-auto">
    <div class="col-md-12">
        <h2 class="text-secondary my-3">
            Editar Propuesta de Trabajo
        </h2>
        <div class="card">
            <div class="card-body">
                <form asp-controller="JobProfile" asp-action="Edit" method="POST">
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label asp-for="StartingDate" class="control-label"></label>
                            <input type="date" asp-for="StartingDate" class="form-control" id="starting-date"/>
                            <span asp-validation-for="StartingDate" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="EndingDate" class="control-label"></label>
                            <input type="date" asp-for="EndingDate" class="form-control" id="ending-date"/>
                            <span asp-validation-for="EndingDate" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-4">
                            <label asp-for="Address" class="control-label"></label>
                            <input type="text" asp-for="Address" class="form-control"  value="@Model.Address"/>
                            <span asp-validation-for="Address" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-4">
                            <label asp-for="Capacity" class="control-label"></label>
                            <input type="number" asp-for="Capacity" class="form-control"  value="@Model.Capacity"/>
                            <span asp-validation-for="Capacity" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-4">
                            <label asp-for="Position" class="control-label"></label>
                            <input type="text" asp-for="Position" class="form-control"  value="@Model.Position"/>
                            <span asp-validation-for="Position" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label asp-for="EmailReceptor" class="control-label"></label>
                            <input type="text" asp-for="EmailReceptor" class="form-control"  value="@Model.EmailReceptor"/>
                            <span asp-validation-for="EmailReceptor" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="Type" class="control-label"></label>
                            <select class="form-control" asp-for="Type">
                                <option value="Relationship">Relación de Dependencia</option>
                                <option value="Internship">Pasantía</option>
                            </select>
                            <span asp-validation-for="Type" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea style="resize:none" type="text" asp-for="Description" class="form-control">@Model.Description</textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group row justify-content-center">
                        <input type="submit" value="Editar" class="btn btn-primary w-75" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function() {
        $('select').val(@Model.Type).change();
            
        const startingDate = document.getElementById('starting-date')
        const endingDate = document.getElementById('ending-date')

        startingDate.value = formatDate(@Model.StartingDate); 
        endingDate.value = formatDate(@Model.EndingDate);
    },
    });

    function formatDate(date) {
      return (
        [
          date.getFullYear(),
          padTo2Digits(date.getMonth() + 1),
          padTo2Digits(date.getDate()),
        ].join('-')
      );
    }

</script>