WebMVC/Controllers/LogoutController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

namespace WebMVC.Controllers
{
    public class LogoutController : Controller
    {
        public IActionResult Index()
        {
            HttpContext.Session.Clear();
            return Redirect("/login");
        }
    }
}

WebMVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>
<html class="h-100 mh-100" lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BolsaTrabajo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    <style>
        li:hover{
            cursor: pointer;
        }
    </style>
</head>
<body style="background:#E3E2E2" class="mb-0 h-100 mh-100 overflow-hidden">
    @if(Context.Session.GetString("Id") != null )
    {
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Bolsa de Trabajo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            
            <ul class="navbar-nav mr-auto">
                    @if(Context.Session.GetString("Type") == "Person")
                    {                        
                    <li class="nav-item dropdown">
                        <a class="dropdown-item" asp-controller="Person" asp-action="Applications">Aplicaciones</a>
                    </li>
                    }

                    else{
                    <li class="nav-item dropdown">
                        <a class="dropdown-item" asp-controller="Company" asp-action="Proposals">Propuestas</a>
                    </li> 
                    }

                    @if (Context.Session.GetString("IsAdmin") == "True"){
                        <li class="dropdown">
                          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Admin
                          </button>
                          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" asp-controller="Person" asp-action="Index">Personas</a>
                            <a class="dropdown-item" asp-controller="Company" asp-action="Index">Empresas</a>
                          </div>
                        </li>
                    }
            </ul>

            <div class="dropdown show">
                <a class="btn btn-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        @Context.Session.GetString("Name") @if (Context.Session.GetString("Type") == "Person")
                        {
                            @Context.Session.GetString("Surname")
                        }  
                    </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    @if (Context.Session.GetString("Type") == "Person")
                    {
                        <a class="dropdown-item" asp-controller="Person" asp-action="Profile">Perfil</a>
                    } else
                    {
                        <a class="dropdown-item" asp-controller="Company" asp-action="Profile">Perfil</a>
                    }  
                        <a class="dropdown-item" asp-controller="Logout" asp-action="Index">Salir</a>
                </div>
            </div>
        </div>
    </nav>
    }

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <div class="container-fluid h-100">
        <main role="main" class="h-100">
            @RenderBody()
        </main>
    </div>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>